file_logging:
  format: "%(asctime)s [%(levelname)s] %(message)s - module:%(module)s"
  level: WARN
  file_location: "loggers/logs/logfile.log"
console_logging:
  format: "%(asctime)s [%(levelname)s] %(message)s - module:%(module)s"
  level: INFO